services:
  pg:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: life-cycle
    volumes:
      - life-cycle-db:/var/lib/postgresql/data

volumes:
  life-cycle-db:
    name: life-cycle-db
